### ISSUE TITLE
Noise Error

### ISSUE THREAD

**Issue by ChandlerAx** [IceCreamYou/THREE.Terrain#37]
Uncaught TypeError: Cannot set properties of undefined (setting 'noise')
    at THREE.Terrain.min.js:7:27
    at THREE.Terrain.min.js:7:2257

**Comment by IceCreamYou** [comment]
Hi there. This issue does not contain enough information to respond usefully. Please identify if this is a bug report or support request, what code you tried that resulted in this error, what version of Three.js you're using, anything you attempted to solve the problem, etc.

Also, debugging will be easier if you use the non-minified version.
